import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tech Blogs | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-4xl text-gray-600">
          Welcome to My Tech Blogs
        </h1>
        <h2></h2>
      </main>

      <footer className={styles.footer}>
        <p>All Rights reserved to Tech Blogs</p>
      </footer>
    </div>
  )
}
