import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tech Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <h1 className=" text-5xl">
          Welcome to My Tech Blogs
        </h1>
      </main>

      <footer className={styles.footer}>
        <p>All Rights reserved to Tech Blogs</p>
      </footer>
    </div>
  )
}
