import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="w-5/6 mx-auto">
      <Head>
        <title>Tech Blogs | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="mx-auto p-32 pt-5">
        <h1 className="text-4xl text-center text-gray-600 pb-5">
          Welcome to My Tech Blogs
        </h1>
        <h2 className=' text-2xl font-mono font-light'>Latest Blogs</h2>
      </main>
    </div>
  );
}
